"""add_received_status_and_warehouse_to_pr

Revision ID: de9fd1dba89a
Revises: db4443a2279a
Create Date: 2026-04-04 22:29:29.406424

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de9fd1dba89a"
down_revision: Union[str, Sequence[str], None] = "db4443a2279a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase_request_items", sa.Column("warehouse_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "purchase_request_items", "warehouses", ["warehouse_id"], ["id"]
    )
    op.add_column(
        "purchase_requests", sa.Column("received_by", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "purchase_requests", sa.Column("received_at", sa.DateTime(), nullable=True)
    )
    op.create_foreign_key(None, "purchase_requests", "users", ["received_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "purchase_requests_received_by_fkey", "purchase_requests", type_="foreignkey"
    )
    op.drop_column("purchase_requests", "received_at")
    op.drop_column("purchase_requests", "received_by")
    op.drop_constraint(
        "purchase_request_items_warehouse_id_fkey",
        "purchase_request_items",
        type_="foreignkey",
    )
    op.drop_column("purchase_request_items", "warehouse_id")
    # ### end Alembic commands ###
