"""add user fks to purchase requests

Revision ID: f9f527e01246
Revises: e1733bef0967
Create Date: 2026-03-19 17:51:04.901954

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9f527e01246"
down_revision: Union[str, Sequence[str], None] = "e1733bef0967"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_purchase_requests_created_by",
        "purchase_requests",
        "users",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_purchase_requests_rejected_by",
        "purchase_requests",
        "users",
        ["rejected_by"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_purchase_requests_approved_by",
        "purchase_requests",
        "users",
        ["approved_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_purchase_requests_approved_by", "purchase_requests", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_purchase_requests_rejected_by", "purchase_requests", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_purchase_requests_created_by", "purchase_requests", type_="foreignkey"
    )
    # ### end Alembic commands ###
